name: Build & Push Images

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Haskell
        uses: docker/build-push-action@v5
        with:
          context: ./haskell-engine
          file: ./haskell-engine/Dockerfile.haskell-engine
          push: true
          tags: danielhaas21/mathbit-haskell:latest

      - name: Build & Push API
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./web-api/Dockerfile.web-api
          push: true
          tags: danielhaas21/mathbit-api:latest

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./web-app/Dockerfile.web-app
          push: true
          tags: danielhaas21/mathbit-frontend:latest

      - name: Run docker compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/mathbit

            docker compose pull
            docker compose up -d --remove-orphans
