name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Copy project to server
      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "."
          target: "~/mathbit"
          ignore: | # we ignore the entire tests package
              .github
              .gitignore
              node_modules
              **/node_modules
              **/docs
              tests
              **/dist
              **/.env

      # Execute deployment commands
      - name: Run docker compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/mathbit
            
            # Replace env files
            mv web-app/.env.prod web-app/.env
            mv web-api/.env.prod web-api/.env

            docker compose down
            docker compose up -d --build